# makefile 03
all : test1.o test2.o test3.o
	cc -o test1 test1.o
	cc -o test2 test2.o
	cc -o test3 test3.o

test1.o :
test2.o :
test3.o :
.PHONY : clean
clean:
	rm -f test1.o test2.o test3.o test1 test2 test3