# makefile 05

all : test5-1 test5-2 test5-3

test5-1	: 	test5-1.c
	gcc -o test5-1 test5-1.c
test5-2	:	test5-2.c
	gcc -o test5-2 test5-2.c
test5-3	:	test5-3.c
	gcc -o test5-3 test5-3.c

clean:
	rm -f *.o test5-1 test5-2 test5-3