all	:	test1-1 test1-2 test1-3
test1-1	:	test1-1.c
	gcc test1-1.c -o test1-1
test1-2	:	test1-2.c
	gcc test1-2.c -o test1-2
test1-3	:	test1-3.c
	gcc test1-3.c -o test1-3

clean	:
	rm -rf test1-1 test1-2 test1-3